### ISSUE TITLE
Moving some selected man pages from "1" to "8" since their tools are in sbin

### ISSUE THREAD

**Issue by frank-heimes** [ibm-s390-linux/s390-tools#135]
Would it make sense to consider moving the man pages for:
dbginfo.sh
lscpumf
lshwc
zfcpdbf
and
zipl-switch-to-blscfg
from "1" to "8"?
Since these tools are currently located in sbin (system binaries), which indicates them as system administration commands, but they currently belong to "1" (User commands).

Right now lintian (lintian -EvIL +pedantic) reports:
P: s390-tools: manual-page-for-system-command sbin/dbginfo.sh
P: s390-tools: manual-page-for-system-command sbin/lscpumf
P: s390-tools: manual-page-for-system-command sbin/lshwc
P: s390-tools: manual-page-for-system-command sbin/zfcpdbf
P: s390-tools: manual-page-for-system-command sbin/zipl-switch-to-blscfg

**Comment by steffen-maier** [comment]
I can only comment on zfcpdbf:
It is indeed a sysadmin command and makes use of /sys/kernel/debug/... which is only accessible to root. So I don't object to moving its man page to section 8 (rename [`scripts/zfcpdbf.1`](https://github.com/ibm-s390-linux/s390-tools/blob/master/scripts/zfcpdbf.1), update [`scripts/Makefile`](https://github.com/ibm-s390-linux/s390-tools/blob/master/scripts/Makefile); but it would also affect all existing packaging!).

**Comment by ifranzki** [comment]
Regarding `zcryptstats`: It utilizes `/dev/chsc` which I guess can only be accessed by root. So it is intentionally a system command. Thus section 8 seems correct to me, the file is named `zcryptstats.8` and is installed into `man8`. Also, at least on my system, it is installed into `/usr/sbin` which seems correct, no? 

But I see what's the problem. Inside the man page it claims to be in section 1:
`.TH ZCRYPTSTATS 1 "January 2019" "s390-tools"`
This should probably be `8` instead of `1`.
